server:
  port: 8765
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: shop_consumer_feign
  datasource:
      username: root
      password: 1
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://169.254.39.117:3306/shop?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=GMT
      type: com.alibaba.druid.pool.DruidDataSource
  redis:
      host: 169.254.39.117
      port: 6379
      database: 0
      password: 123
      timeout: 1000
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
  mail:
    host: smtp.163.com
    username: xiaogengi@163.com
    password: xiaogeng0806
    default-encoding: UTF-8
    auth: true
    starttls:
      enable: true
    timeout: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
